### ISSUE TITLE
[TS-589] [Question] how to dispute jackson linter flagged issue?

### ISSUE THREAD

**Issue by simkimsia** [codacy/codacy-jackson-linter#26]
https://app.codacy.com/gh/GreenDeploy-io/greendeploy-django-ltree/file/98440157720/issues/source?bid=37784605&fileBranchId=37784605#l9

i disagree that the jackson linter flagged this.

How do I dispute this? According to vscode, what I did was valid JSON.

Also how to get jackson linter advise on how to improve it?

<img width="1145" alt="image" src="https://github.com/codacy/codacy-jackson-linter/assets/245021/5664c128-e65d-4df1-af37-028ea74ab4b2">
Added screenshot in case it's later solved by me

i suspect the issue is due to the trailing comma. Is there a way to ALLOW_TRAILING_COMMA?

See https://stackoverflow.com/a/76202496/80353

**Comment by simkimsia** [comment]
This is related to https://github.com/zardoy/vscode-fix-all-json/issues/20#issuecomment-1723937813

so jackson linter should skip those that are using JSONC. Not sure how to detect whether a file is json or jsonc

**Comment by stefanvacareanu7** [comment]
Hi there,

Thanks for reaching our community!

As @simkimsia shared, this is related to jackson linter analyzing .json files vs .jsonc files.

By default, jackson linter analyzes only .json files, so modifying a file with .jsonc will make the tool skip that file.

Since there is no other issue in this issue, I am closing it.

Feel free to contact us here or at support@codacy.com for any further questions.

Best,
Stefan

**Comment by simkimsia** [comment]
Sorry this is not clear to me

Are you telling me I should rename a file as .jsonc?

**Comment by simkimsia** [comment]
![image](https://github.com/codacy/codacy-jackson-linter/assets/245021/49f39ff4-87ba-4f85-b1bd-4410ff54f7b0)

As you can see here, jsonc is a superset of json and Microsoft uses json file extension for its vscode settings

As a developer tool, shouldn't you be aware of this?

Like in my original question, I'm unaware of how to tell Jackson or codacy to skip vscode settings.json

**Comment by simkimsia** [comment]
https://github.com/microsoft/vscode/issues/79744

Indicates there is no such thing as a jsonc file extension for jsonc formatted json file
